export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",

  ONBOARDING_1 = 'ONBOARDING_1',
  ONBOARDING_2 = 'ONBOARDING_2',
  ONBOARDING_3 = 'ONBOARDING_3',
  ONBOARDING_4 = 'ONBOARDING_4',
  ONBOARDING_NEXT = 'ONBOARDING_NEXT',
  ONBOARDING_SKIP = 'ONBOARDING_SKIP',
  ONBOARDING_DONE = 'ONBOARDING_DONE',
}
