export enum LocalizationKey {
  WELCOME = "welcome",
  HOME = "home",
  START = "start",
  LOADING = "loading",

  ONBOARDING_1 = 'ONBOARDING_1',
  ONBOARDING_2 = 'ONBOARDING_2',
  ONBOARDING_3 = 'ONBOARDING_3',
  ONBOARDING_4 = 'ONBOARDING_4',
  ONBOARDING_NEXT = 'ONBOARDING_NEXT',
  ONBOARDING_SKIP = 'ONBOARDING_SKIP',
  ONBOARDING_DONE = 'ONBOARDING_DONE',

  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',

  FAVORITE = 'FAVORITE',
  SEARCH = 'SEARCH',
  PROFILE = 'PROFILE',


  SEARCH_RESULT = 'SEARCH_RESULT',
  ABOUT = 'ABOUT',
  RECIPE = 'RECIPE',
  REVIEW = 'REVIEW',
  LIST = 'LIST',
  YOUR_LIST = 'YOUR_LIST',
  CREATE_NEW_LIST = 'CREATE_NEW_LIST',
  ADD_DISH = 'ADD_DISH',
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
}
